wallpaper {
    monitor = eDP-1
    path = ~/dotfiles/assets/wallpaper.jpg
    fit_mode = cover
}

# preload = /home/binamra/dotfiles/assets/wallpaper.jpg
# wallpaper = eDP-1,/home/binamra/dotfiles/assets/wallpaper.jpg

